apiVersion: apps/v1
kind: Deployment
metadata:
 name: real-world-app-release
 labels:
   app: real-world-app-release
spec:
 replicas: 1
 selector:
   matchLabels:
     app: real-world-app-release
 template:
   metadata:
     labels:
       app: real-world-app-release
   spec:
     containers:
     - name: real-world-app-release
       image: jeffjojerjonescatulay/real-world-app:v1.0.1
       ports:
       - containerPort: 80