apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-argo-demo-cd
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/JeffJojerJonesCatulay/gitops-argocd.git
    targetRevision: HEAD
    path: local-argo-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true