apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: real-world-app-prod-cd
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/JeffJojerJonesCatulay/gitops-argocd.git
    targetRevision: main
    path: real-world-app/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true