apiVersion: v1
kind: Service
metadata:
  name: real-world-app-prod-service
  namespace: prod
spec:
  selector:
    app: real-world-app-prod
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 80
  type: NodePort
