apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-api-dev-cd
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/JeffJojerJonesCatulay/gitops-argocd.git
    targetRevision: dev
    path: employee-api/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true