apiVersion: apps/v1
kind: Deployment
metadata:
 name: employee-api-dev
 labels:
   app: employee-api-dev
spec:
 replicas: 1
 selector:
   matchLabels:
     app: employee-api-dev
 template:
   metadata:
     labels:
       app: employee-api-dev
   spec:
     containers:
     - name: employee-api-dev
       image: 961776040935.dkr.ecr.us-east-1.amazonaws.com/app-images-global-30620849894:v1.0.11
       ports:
       - containerPort: 9010
       env:
       - name: EMP_SERVER_PORT
         valueFrom:
           secretKeyRef:
             name: employee-api-secrets
             key: EMP_SERVER_PORT
       - name: EMP_DB_URL
         valueFrom:
           secretKeyRef:
             name: employee-api-secrets
             key: EMP_DB_URL
       - name: EMP_DB_USERNAME
         valueFrom:
           secretKeyRef:
             name: employee-api-secrets
             key: EMP_DB_USERNAME
       - name: EMP_DB_PASSWORD
         valueFrom:
           secretKeyRef:
             name: employee-api-secrets
             key: EMP_DB_PASSWORD 
